const data = [
    {
        name: 'Mixmax',
        budget_name: 'Software subscription',
        owner_id: 1,
        spent: {
            value: 100,
            currency: 'SGD',
        },
        available_to_spend: {
            value: 1000,
            currency: 'SGD',
        },
        card_type: 'burner',
        expiry: '9 Feb',
        limit: 100,
        status: 'active',
    },
    {
        name: 'Quickbooks',
        budget_name: 'Software subscription',
        owner_id: 2,
        spent: {
            value: 50,
            currency: 'SGD',
        },
        available_to_spend: {
            value: 250,
            currency: 'SGD',
        },
        card_type: 'subscription',
        limit: 10,
        status: 'active',
    },
    {
        name: 'Slack',
        budget_name: 'Software subscription',
        owner_id: 3,
        spent: {
            value: 80,
            currency: 'SGD',
        },
        available_to_spend: {
            value: 500,
            currency: 'SGD',
        },
        card_type: 'burner',
        expiry: '15 Mar',
        limit: 200,
        status: 'blocked',
    },
    {
        name: 'Zoom',
        budget_name: 'Software subscription',
        owner_id: 4,
        spent: {
            value: 120,
            currency: 'SGD',
        },
        available_to_spend: {
            value: 800,
            currency: 'SGD',
        },
        card_type: 'subscription',
        limit: 20,
        status: 'active',
    },
    {
        name: 'Trello',
        budget_name: 'Software subscription',
        owner_id: 1,
        spent: {
            value: 40,
            currency: 'SGD',
        },
        available_to_spend: {
            value: 300,
            currency: 'SGD',
        },
        card_type: 'burner',
        expiry: '30 Apr',
        limit: 150,
        status: 'active',
    },
    {
        name: 'Asana',
        budget_name: 'Software subscription',
        owner_id: 2,
        spent: {
            value: 60,
            currency: 'SGD',
        },
        available_to_spend: {
            value: 400,
            currency: 'SGD',
        },
        card_type: 'subscription',
        limit: 15,
        status: 'blocked',
    },
    
    {
    name: 'GitHub',
    budget_name: 'Software subscription',
    owner_id: 5,
    spent: {
      value: 90,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 600,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 25,
    status: 'active',
  },
  {
    name: 'Dropbox',
    budget_name: 'Software subscription',
    owner_id: 6,
    spent: {
      value: 70,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 450,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '10 May',
    limit: 120,
    status: 'active',
  },
  {
    name: 'Google Workspace',
    budget_name: 'Software subscription',
    owner_id: 7,
    spent: {
      value: 110,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 900,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '20 Jun',
    limit: 180,
    status: 'blocked',
  },
  {
    name: 'Salesforce',
    budget_name: 'Software subscription',
    owner_id: 8,
    spent: {
      value: 140,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 750,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 30,
    status: 'active',
  },
  {
    name: 'Notion',
    budget_name: 'Software subscription',
    owner_id: 9,
    spent: {
      value: 45,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 280,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '5 Jul',
    limit: 100,
    status: 'active',
  },
  {
    name: 'Adobe Creative Cloud',
    budget_name: 'Software subscription',
    owner_id: 10,
    spent: {
      value: 75,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 550,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 20,
    status: 'active',
  },
  {
    name: 'Slack',
    budget_name: 'Software subscription',
    owner_id: 11,
    spent: {
      value: 70,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 400,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '15 Sep',
    limit: 150,
    status: 'active',
  },
  {
    name: 'Microsoft 365',
    budget_name: 'Software subscription',
    owner_id: 12,
    spent: {
      value: 105,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 700,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 25,
    status: 'blocked',
  },
  {
    name: 'Monday.com',
    budget_name: 'Software subscription',
    owner_id: 13,
    spent: {
      value: 55,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 350,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '22 Oct',
    limit: 120,
    status: 'active',
  },
  {
    name: 'Jira',
    budget_name: 'Software subscription',
    owner_id: 14,
    spent: {
      value: 95,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 600,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 15,
    status: 'active',
    },
  {
  name: 'Airtable',
    budget_name: 'Software subscription',
    owner_id: 15,
    spent: {
      value: 85,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 600,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 25,
    status: 'active',
  },
  {
    name: 'Evernote',
    budget_name: 'Software subscription',
    owner_id: 16,
    spent: {
      value: 60,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 350,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '5 Dec',
    limit: 120,
    status: 'active',
  },
  {
    name: 'Atlassian Confluence',
    budget_name: 'Software subscription',
    owner_id: 17,
    spent: {
      value: 110,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 800,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '10 Jan',
    limit: 180,
    status: 'blocked',
  },
  {
    name: 'Dropbox Business',
    budget_name: 'Software subscription',
    owner_id: 18,
    spent: {
      value: 140,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 700,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 30,
    status: 'active',
  },
  {
    name: 'Notion',
    budget_name: 'Software subscription',
    owner_id: 19,
    spent: {
      value: 45,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 280,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '5 Jul',
    limit: 100,
    status: 'active',
  },
  {
    name: 'Adobe Acrobat DC',
    budget_name: 'Software subscription',
    owner_id: 20,
    spent: {
      value: 75,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 550,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 20,
    status: 'active',
  },
  {
    name: 'Slack',
    budget_name: 'Software subscription',
    owner_id: 21,
    spent: {
      value: 70,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 400,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '15 Sep',
    limit: 150,
    status: 'active',
  },
  {
    name: 'Microsoft Teams',
    budget_name: 'Software subscription',
    owner_id: 22,
    spent: {
      value: 105,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 700,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 25,
    status: 'blocked',
  },
  {
    name: 'Todoist',
    budget_name: 'Software subscription',
    owner_id: 23,
    spent: {
      value: 55,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 350,
      currency: 'SGD',
    },
    card_type: 'burner',
    expiry: '22 Oct',
    limit: 120,
    status: 'active',
  },
  {
    name: 'Basecamp',
    budget_name: 'Software subscription',
    owner_id: 24,
    spent: {
      value: 95,
      currency: 'SGD',
    },
    available_to_spend: {
      value: 600,
      currency: 'SGD',
    },
    card_type: 'subscription',
    limit: 15,
    status: 'active',
  },

];

module.exports = data;